apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: geekembly
  generateName: kaniko-docker-workflow-
spec:
  entrypoint: start
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 4Gi
  volumes:
    - name: reg-auth-vol
      secret:
        secretName: kaniko-auth
    - name: ssh-vol
      secret:
        secretName: github-ssh-key2

  templates:
    - name: kaniko-build
      container:
        image: gcr.io/kaniko-project/executor:latest
        command:
          - /kaniko/executor
        args:
          - --dockerfile=Dockerfile
          - --context=/workdir/geekembly
          - --destination=registry-svc.registry/geekembly:latest
          - --insecure=true
        volumeMounts:
          - name: workdir
            mountPath: /workdir
          - name: reg-auth-vol
            mountPath: /kaniko/.docker
        resources:
          limits:
            ephemeral-storage: 8Gi
          requests:
            memory: 2Gi

    - name: github-clone
      inputs:
      script:
        image: bitnami/git:latest
        command: [sh]
        source: |
          #!/bin/bash
          mkdir -p /root/.ssh
          cp /github/id_rsa /root/.ssh/
          chmod 600 /root/.ssh/id_rsa
          touch /root/.ssh/known_hosts && ssh-keyscan github.com >> /root/.ssh/known_hosts

          cd /workdir
          git clone git@github.com:Cih2001/geekembly.git

        volumeMounts:
          - name: workdir
            mountPath: /workdir
          - name: ssh-vol
            mountPath: /github

    - name: start
      steps:
        - - name: clone
            template: github-clone
        - - name: build-and-push
            template: kaniko-build
