apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: geekembly
  name: argocd-sync-and-wait
  annotations:
    workflows.argoproj.io/description: >-
      This task syncs (deploys) an Argo CD application and waits for it to be healthy.
      If specified, you can force sync a deployment.
    workflows.argoproj.io/tags: argocd
    workflows.argoproj.io/version: ">= 2.9.0"
spec:
  entrypoint: argocd-sync-and-wait
  templates:
    - name: argocd-sync-and-wait
      inputs:
        parameters:
          - name: argocd-version
            value: v1.6.0
          - name: application-name
          - name: revision
            value: HEAD
          - name: deployment-name
            description: when provided, the specified deployment will be forced synced.
            default: ""
          - name: flags
            description: additional flags to pass to argocd
            value: --
          - name: argocd-server-address
          - name: argocd-credentials-secret
      script:
        image: argoproj/argocd:{{inputs.parameters.argocd-version}}
        command: [bash]
        env:
          - name: ARGOCD_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: "{{inputs.parameters.argocd-credentials-secret}}"
                key: token
                optional: true
          - name: ARGOCD_SERVER
            value: "{{inputs.parameters.argocd-server-address}}"
          - name: DEPLOYMENT_NAME
            value: "{{inputs.parameters.deployment-name}}"
        source: |
          #!/bin/bash

          set -euo pipefail

          if [ -z $ARGOCD_AUTH_TOKEN ]; then
            echo "ARGOCD_AUTH_TOKEN must be specified."
            exit 1
          fi 

          echo "Running as ArgoCD User:"
          argocd account get-user-info {{inputs.parameters.flags}}

          argocd app sync {{inputs.parameters.application-name}} --revision {{inputs.parameters.revision}} {{inputs.parameters.flags}}
          if [ -n "$DEPLOYMENT_NAME" ]; then 
            echo "force syncing $DEPLOYMENT_NAME"
            argocd app sync {{inputs.parameters.application-name}} --revision {{inputs.parameters.revision}} --resource apps:Deployment:$DEPLOYMENT_NAME --force {{inputs.parameters.flags}}
          fi

          argocd app wait {{inputs.parameters.application-name}} --health {{inputs.parameters.flags}}
