apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: geekembly
  name: geekembly-dpl
spec:
  selector:
    matchLabels:
      app: geekembly
  replicas: 1
  template:
    metadata:
      labels:
        app: geekembly
    spec:
      containers:
        - name: geekembly
          image: docker.registry.geekembly.com/geekembly:latest
          ports:
            - containerPort: 1313
          command: ["./scripts/run.sh"]
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  namespace: geekembly
  name: geekembly-svc
spec:
  ports:
    - port: 80
      targetPort: 1313
      protocol: TCP
  selector:
    app: geekembly
