apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - cicd.yaml
  - events.yaml
  - namespace.yaml
  - secrets.yaml
  - workflows.yaml

namespace: geekembly
images:
  - name: geekembly
    newName: docker.registry.geekembly.com/geekembly
    newTag: "7b4d9ce90ce32ef53cbff5d81eeef1f65fc67ed7"
