apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - cicd.yaml
  - events.yaml
  - namespace.yaml
  - secrets.yaml
  - workflows.yaml
  - servicemonitor.yaml

namespace: geekembly
images:
  - name: geekembly
    newName: docker.registry.geekembly.com/geekembly
    newTag: "69a1bf41beeea31b462c148311fc40b06cea942e"
