apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - cicd.yaml
  - events.yaml
  - namespace.yaml
  - secrets.yaml
  - workflows.yaml
  - servicemonitor.yaml

namespace: geekembly
images:
  - name: geekembly
    newName: docker.registry.geekembly.com/geekembly
    newTag: "a73f9a59146d424d50ba501a798b644e3fe22f3d"
