apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: geekembly-sm
  namespace: geekembly
spec:
  endpoints:
    - port: metrics
      interval: 30s
  selector:
    matchLabels:
      app: geekembly
