apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: argo-workflows-admin
  namespace: geekembly
rules:
  - apiGroups:
      - argoproj.io
    resources:
      # This one is requred for workflows to work
      - workflowtaskresults
      # These are needed for sensors to work
      - workflows
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: workflows-default-admin-rb
  namespace: geekembly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflows-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: geekembly
